### PR TITLE
Handle Slurm MaxArraySize-BRIDGED Mode

### PR DESCRIPTION
**Pull request by ZDu-IDM**
This PR aims to address
Ticket: Potential issue with max count of simulations in slurm platform #1998 

- Handled the MaxArraySize in Bridged mode case of SlurmPlatform
- Fully support MaxArraySize in cancel experiment functionality
- Fully support MaxArraySize in idmtools-calibra applications

### CODE REVIEW

**Review by devclinton — APPROVED** [review]

**Comment by shchen-idmod** [comment]
Got error:
```
(idmtools_5_19) shchen@internal.idm.ctr@ipapvwks22:~/github/idmtools/examples/native_slurm$ python python_sims_array_size.py
You are using a development version of idmtools, version 1.7.6+nightly!
INI File Used: /home/shchen/github/idmtools/examples/idmtools.ini

[SLURM_BRIDGED]
{
   "mode": "bridged",
   "job_directory": "/home/shchen/example"
}
Commissioning Simulations: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:00<00:00, 154.77simulation/s]
Result for /home/shchen/.idmtools/singularity-bridge/4b7f93c7-46b1-422e-b23d-784cd40c2214.json: {
    "output": "No command specified. You must specify either sbatch, scancel, or verify",
    "status": "error"
}
job_directory: /home/shchen/example
suite: f14842a8-8195-440a-8016-d5dfb0783dad
experiment: cadc3ca5-9772-4b3c-af86-46a10ff5102b
Slurm Job Ids: None

You may try the following command to check simulations running status:
  idmtools slurm /home/shchen/example status --exp-id cadc3ca5-9772-4b3c-af86-46a10ff5102b
Waiting on Experiment python example to Finish running:   0%|                                                                                                                                                                                                                                                                                                               | 0/150 [00:00<?, ?simulation/s]

```

**Comment by ZDu-IDM** [comment]
> Got error:
> 
> ```
> (idmtools_5_19) shchen@internal.idm.ctr@ipapvwks22:~/github/idmtools/examples/native_slurm$ python python_sims_array_size.py
> You are using a development version of idmtools, version 1.7.6+nightly!
> INI File Used: /home/shchen/github/idmtools/examples/idmtools.ini
> 
> [SLURM_BRIDGED]
> {
>    "mode": "bridged",
>    "job_directory": "/home/shchen/example"
> }
> Commissioning Simulations: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [00:00<00:00, 154.77simulation/s]
> Result for /home/shchen/.idmtools/singularity-bridge/4b7f93c7-46b1-422e-b23d-784cd40c2214.json: {
>     "output": "No command specified. You must specify either sbatch, scancel, or verify",
>     "status": "error"
> }
> job_directory: /home/shchen/example
> suite: f14842a8-8195-440a-8016-d5dfb0783dad
> experiment: cadc3ca5-9772-4b3c-af86-46a10ff5102b
> Slurm Job Ids: None
> 
> You may try the following command to check simulations running status:
>   idmtools slurm /home/shchen/example status --exp-id cadc3ca5-9772-4b3c-af86-46a10ff5102b
> Waiting on Experiment python example to Finish running:   0%|                                                                                                                                                                                                                                                                                                               | 0/150 [00:00<?, ?simulation/s]
> ```

Fixed (add missing command), please verify, thanks!

**Comment by shchen-idmod** [comment]
Cancel seems not working with dependency=True. It will get stocked

**Review by shchen-idmod — APPROVED** [review]
Tested all features.

**Pull request merged**
